## Integral

In [1]:
import sympy as sy
import numpy as np

### Fungsi 1

#### Symbolic Method

In [2]:
x = sy.Symbol('x')
f1 = 3*x**2 - 6*x + 3
f1

3*x**2 - 6*x + 3

In [3]:
sy.integrate(f1)

x**3 - 3*x**2 + 3*x

#### Numerical Method
misal mencari luas area di bawah kurva fungsi f1 untuk x=-3 sampai x=1

In [7]:
# numerical function

from scipy import integrate

def f1(x):
  return 3*x**2 - 6*x + 3
  
A = integrate.quad(f1,-3,1)
print(A)

(64.0, 7.105427357601002e-13)


In [8]:
# numerical array

x = np.linspace(-3,1)
y = f1(x)

B = integrate.trapz(y,x) #trapezoid
B

64.01332778009163

Luas area di bawah kurva fungsi f1 untuk x=-3 sampai x=1 adalah 64.0

### Fungsi 2

#### Symbolic Method

In [5]:
x = sy.Symbol('x')
f2 = 8*x**3 - x**2 + 5*x - 1
f2

8*x**3 - x**2 + 5*x - 1

In [6]:
sy.integrate(f2)

2*x**4 - x**3/3 + 5*x**2/2 - x

#### Numerical Method
misal mencari luas area di bawah kurva fungsi f2 untuk x=-2 sampai x=4

In [11]:
# numerical function

def f2(x):
  return 8*x**3 - x**2 + 5*x - 1
  
C = integrate.quad(f2,-2,4)
print(C)

(480.0, 6.367436714970997e-12)


In [12]:
# numerical array

x = np.linspace(-2,4)
y = f2(x)

D = integrate.simps(y,x) # simpson rule
D

480.0070378838749

Luas area di bawah kurva fungsi f2 untuk x=-2 sampai x=4 adalah 480.0